#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define QUICK_TAP_TERM 130
#define TAPPING_TERM 210
#define PERMISSIVE_HOLD

//#    ifdef RGB_MATRIX_ENABLE
#        undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#        undef ENABLE_RGB_MATRIX_BREATHING
#        undef ENABLE_RGB_MATRIX_BAND_SAT
#        undef ENABLE_RGB_MATRIX_BAND_VAL
#        undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#        undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#        undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#        undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#        undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#        undef ENABLE_RGB_MATRIX_DUAL_BEACON
// enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
#        undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#        undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#        undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
//#    endif
